version: "3.8"

services:
  trb_mysql:
    image: mysql:8.0
    container_name: TRB_MYSQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: trb
      MYSQL_USER: trb
      MYSQL_PASSWORD: trbmysql
    ports:
      - "3307:3306"
    volumes:
      - trb_mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  trb_mysql_data:
